manifest:
  version: 0.8

  projects:
    - name: zephyr
      url: https://github.com/XenuIsWatching/zephyr
      revision: counter-cap-dev
      import:
        file: west.yml
        path-prefix: deps
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_st
          - hal_stm32

  self:
    path: app
